test_that("check_string_param", {
  expect_no_error(check_string_param("name", "value"))
  expect_no_error(check_string_param("name", "value", required = FALSE))
  expect_error(check_string_param("name", 5))
  expect_error(check_string_param("name", 5, required = FALSE))
  expect_error(check_string_param("name", NULL))
  expect_no_error(check_string_param("name", NULL, required = FALSE))
  expect_error(check_string_param("name", c("value1", "value2")))
  expect_error(check_string_param("name", c("value1", "value2"), required = FALSE))
})

test_that("check_character_param", {
  expect_no_error(check_character_param("name", "value"))
  expect_no_error(check_character_param("name", "value", required = FALSE))
  expect_error(check_character_param("name", 5))
  expect_error(check_character_param("name", 5, required = FALSE))
  expect_error(check_character_param("name", NULL))
  expect_no_error(check_character_param("name", NULL, required = FALSE))
  expect_no_error(check_character_param("name", c("value1", "value2")))
  expect_no_error(check_character_param("name", c("value1", "value2"), required = FALSE))
  expect_error(check_character_param("name", list("value1", 5)))
})

test_that("check_scalar_integerish_param", {
  expect_no_error(check_scalar_integerish_param("name", 5))
  expect_no_error(check_scalar_integerish_param("name", 5, required = FALSE))
  expect_error(check_scalar_integerish_param("name", "value"))
  expect_error(check_scalar_integerish_param("name", "value", required = FALSE))
  expect_error(check_scalar_integerish_param("name", NULL))
  expect_no_error(check_scalar_integerish_param("name", NULL, required = FALSE))
  expect_error(check_scalar_integerish_param("name", c(5, 6)))
  expect_error(check_scalar_integerish_param("name", c(5, 6), required = FALSE))
})

test_that("check_integerish_param", {
  expect_no_error(check_integerish_param("name", 5))
  expect_no_error(check_integerish_param("name", 5, required = FALSE))
  expect_error(check_integerish_param("name", "value"))
  expect_error(check_integerish_param("name", "value", required = FALSE))
  expect_error(check_integerish_param("name", NULL))
  expect_no_error(check_integerish_param("name", NULL, required = FALSE))
  expect_no_error(check_integerish_param("name", c(5, 6)))
  expect_no_error(check_integerish_param("name", c(5, 6), required = FALSE))
  expect_error(check_integerish_param("name", list(5, 6)))
})

test_that("check_scalar_date_param", {
  expect_no_error(check_scalar_date_param("name", "2020-01-01"))
  expect_no_error(check_scalar_date_param("name", "2020-01-01", required = FALSE))
  expect_no_error(check_scalar_date_param("name", 20200101))
  expect_no_error(check_scalar_date_param("name", 20200101, required = FALSE))
  # expect_no_error(check_single_date_param("name", as.Date("2020-01-01")))
  # expect_no_error(check_single_date_param("name", as.Date("2020-01-01"), required = FALSE))
  expect_error(check_scalar_date_param("name", NULL))
  expect_no_error(check_scalar_date_param("name", NULL, required = FALSE))
  expect_error(check_scalar_date_param("name", c(20200101, 20200101)))
  expect_error(check_scalar_date_param("name", list(20200101, 20200101)))
  # expect_error(check_single_date_param("name", c("2020-01-01", 20200102, as.Date("2020-01-03"))), "argument is not a datelike")
  # expect_error(check_single_date_param("name", c("2020-01-01", 20200102, as.Date("2020-01-03")), required = FALSE), "argument is not a datelike")
  # expect_error(check_single_date_param("name", list("2020-01-01", 20200102, as.Date("2020-01-03"))), "argument is not a datelike")
  # expect_error(check_single_date_param("name", list("2020-01-01", 20200102, as.Date("2020-01-03")), required = FALSE), "argument is not a datelike")
})

test_that("check_date_param", {
  expect_no_error(check_date_param("name", "2020-01-01"))
  expect_no_error(check_date_param("name", "2020-01-01", required = FALSE))
  expect_no_error(check_date_param("name", 20200101))
  expect_no_error(check_date_param("name", 20200101, required = FALSE))
  # expect_no_error(check_date_param("name", as.Date("2020-01-01")))
  # expect_no_error(check_date_param("name", as.Date("2020-01-01"), required = FALSE))
  expect_error(check_date_param("name", NULL))
  expect_no_error(check_date_param("name", NULL, required = FALSE))

  # expect_no_error(check_date_param("name", c("2020-01-01", 20200102, as.Date("2020-01-03"))))
  # expect_no_error(check_date_param("name", c("2020-01-01", 20200102, as.Date("2020-01-03"))), required = FALSE)
})

test_that("check_single_timeset_param", {
  expect_no_error(check_scalar_timeset_param("name", "2020-01-01"))
  expect_no_error(check_scalar_timeset_param("name", "2020-01-01", required = FALSE))
  expect_no_error(check_scalar_timeset_param("name", 20200101))
  expect_no_error(check_scalar_timeset_param("name", 20200101, required = FALSE))
  expect_no_error(check_scalar_timeset_param("name", epirange(20200101, 20200102)))
  expect_no_error(check_scalar_timeset_param("name", epirange(20200101, 20200102), required = FALSE))
  # expect_no_error(check_single_epirange_param("name", as.Date("2020-01-01")))
  # expect_no_error(check_single_epirange_param("name", as.Date("2020-01-01"), required = FALSE))
  expect_error(check_scalar_timeset_param("name", NULL))
  expect_no_error(check_scalar_timeset_param("name", NULL, required = FALSE))
  expect_error(check_scalar_timeset_param("name", c("2020-01-01", 20200102)))
  expect_error(check_scalar_timeset_param("name", list("2020-01-01")))
})

test_that("check_timeset_param", {
  expect_no_error(check_timeset_param("name", "2020-01-01"))
  expect_no_error(check_timeset_param("name", "2020-01-01", required = FALSE))
  expect_no_error(check_timeset_param("name", 20200101))
  expect_no_error(check_timeset_param("name", 20200101, required = FALSE))
  expect_no_error(check_timeset_param("name", epirange(20200101, 20200102)))
  expect_no_error(check_timeset_param("name", epirange(20200101, 20200102), required = FALSE))
  # expect_no_error(check_epirange_param("name", as.Date("2020-01-01")))
  # expect_no_error(check_epirange_param("name", as.Date("2020-01-01"), required = FALSE))
  expect_error(check_timeset_param("name", NULL))
  expect_no_error(check_timeset_param("name", NULL, required = FALSE))
  expect_no_error(check_timeset_param("name", c(20200101, 20200102)))
  expect_no_error(check_timeset_param("name", c("2020-01-01", 20200102)))
  expect_error(check_timeset_param("name", list("2020-01-01")))
  expect_no_error(check_timeset_param("name", list(epirange(20200101, 20200102), epirange(20200101, 20200102))))
  expect_error(check_timeset_param("name", c(epirange(20200101, 20200102))))
})
