test_that("check_single_string_param", {
  expect_no_error(check_single_string_param("name", "value"))
  expect_no_error(check_single_string_param("name", "value", required = FALSE))
  expect_error(check_single_string_param("name", 5), "argument name is not a single string")
  expect_error(check_single_string_param("name", 5, required = FALSE), "argument name is not a single string")
  expect_error(check_single_string_param("name", NULL), "argument name is not a single string")
  expect_no_error(check_single_string_param("name", NULL, required = FALSE))
  expect_error(check_single_string_param("name", c("value1", "value2")), "argument name is not a single string")
  expect_error(check_single_string_param("name", c("value1", "value2"), required = FALSE), "argument name is not a single string")
})

test_that("check_string_param", {
  expect_no_error(check_string_param("name", "value"))
  expect_no_error(check_string_param("name", "value", required = FALSE))
  expect_error(check_string_param("name", 5), "argument name is not a string")
  expect_error(check_string_param("name", 5, required = FALSE), "argument name is not a string")
  expect_error(check_string_param("name", NULL), "argument name is not a string")
  expect_no_error(check_string_param("name", NULL, required = FALSE))
  expect_no_error(check_string_param("name", c("value1", "value2")))
  expect_no_error(check_string_param("name", c("value1", "value2"), required = FALSE))
  expect_no_error(check_string_param("name", list("value1", "value2")))
  expect_no_error(check_string_param("name", list("value1", "value2"), required = FALSE))
  expect_error(check_string_param("name", list("value1", 5)), "argument name\\[2\\] is not a single string")
})

test_that("check_single_int_param", {
  expect_no_error(check_single_int_param("name", 5))
  expect_no_error(check_single_int_param("name", 5, required = FALSE))
  expect_error(check_single_int_param("name", "value"), "argument name is not a single number")
  expect_error(check_single_int_param("name", "value", required = FALSE), "argument name is not a single number")
  expect_error(check_single_int_param("name", NULL), "argument name is not a single number")
  expect_no_error(check_single_int_param("name", NULL, required = FALSE))
  expect_error(check_single_int_param("name", c(5, 6)), "argument name is not a single number")
  expect_error(check_single_int_param("name", c(5, 6), required = FALSE), "argument name is not a single number")
})

test_that("check_int_param", {
  expect_no_error(check_int_param("name", 5))
  expect_no_error(check_int_param("name", 5, required = FALSE))
  expect_error(check_int_param("name", "value"), "argument name is not a number")
  expect_error(check_int_param("name", "value", required = FALSE), "argument name is not a number")
  expect_error(check_int_param("name", NULL), "argument name is not a number")
  expect_no_error(check_int_param("name", NULL, required = FALSE))
  expect_no_error(check_int_param("name", c(5, 6)))
  expect_no_error(check_int_param("name", c(5, 6), required = FALSE))
  expect_no_error(check_int_param("name", list(5, 6)))
  expect_no_error(check_int_param("name", list(5, 6), required = FALSE))
  expect_error(check_int_param("name", list(5, "value")), "argument name\\[2\\] is not a single number")
})

test_that("check_single_date_param", {
  expect_no_error(check_single_date_param("name", "2020-01-01"))
  expect_no_error(check_single_date_param("name", "2020-01-01", required = FALSE))
  expect_no_error(check_single_date_param("name", 20200101))
  expect_no_error(check_single_date_param("name", 20200101, required = FALSE))
  # expect_no_error(check_single_date_param("name", as.Date("2020-01-01")))
  # expect_no_error(check_single_date_param("name", as.Date("2020-01-01"), required = FALSE))
  expect_error(check_single_date_param("name", NULL), "argument name is not a datelike")
  expect_no_error(check_single_date_param("name", NULL, required = FALSE))
  expect_error(check_single_date_param("name", c(20200101, 20200101)), "argument name is not a datelike")

  expect_error(check_single_date_param("name", list()), "argument name is not a datelike")
  expect_error(check_single_date_param("name", list(), required = FALSE), "argument name is not a datelike")
  # expect_error(check_single_date_param("name", c("2020-01-01", 20200102, as.Date("2020-01-03"))), "argument is not a datelike")
  # expect_error(check_single_date_param("name", c("2020-01-01", 20200102, as.Date("2020-01-03")), required = FALSE), "argument is not a datelike")
  # expect_error(check_single_date_param("name", list("2020-01-01", 20200102, as.Date("2020-01-03"))), "argument is not a datelike")
  # expect_error(check_single_date_param("name", list("2020-01-01", 20200102, as.Date("2020-01-03")), required = FALSE), "argument is not a datelike")
})

test_that("check_date_param", {
  expect_no_error(check_date_param("name", "2020-01-01"))
  expect_no_error(check_date_param("name", "2020-01-01", required = FALSE))
  expect_no_error(check_date_param("name", 20200101))
  expect_no_error(check_date_param("name", 20200101, required = FALSE))
  # expect_no_error(check_date_param("name", as.Date("2020-01-01")))
  # expect_no_error(check_date_param("name", as.Date("2020-01-01"), required = FALSE))
  expect_error(check_date_param("name", NULL), "argument name is not a datelike")
  expect_no_error(check_date_param("name", NULL, required = FALSE))

  expect_error(check_date_param("name", list()), "argument name is not a datelike")
  expect_error(check_date_param("name", list(), required = FALSE), "argument name is not a datelike")
  # expect_no_error(check_date_param("name", c("2020-01-01", 20200102, as.Date("2020-01-03"))))
  # expect_no_error(check_date_param("name", c("2020-01-01", 20200102, as.Date("2020-01-03"))), required = FALSE)
  # expect_no_error(check_date_param("name", list("2020-01-01", 20200102, as.Date("2020-01-03"))))
  # expect_no_error(check_date_param("name", list("2020-01-01", 20200102, as.Date("2020-01-03"))), required = FALSE)
  expect_error(check_date_param("name", list("2020-01-01", 20200102, list())), "argument name\\[3\\] is not a datelike")
})

test_that("check_single_epirange_param", {
  expect_no_error(check_single_epirange_param("name", "2020-01-01"))
  expect_no_error(check_single_epirange_param("name", "2020-01-01", required = FALSE))
  expect_no_error(check_single_epirange_param("name", 20200101))
  expect_no_error(check_single_epirange_param("name", 20200101, required = FALSE))
  expect_no_error(check_single_epirange_param("name", epirange(20200101, 20200102)))
  expect_no_error(check_single_epirange_param("name", epirange(20200101, 20200102), required = FALSE))
  # expect_no_error(check_single_epirange_param("name", as.Date("2020-01-01")))
  # expect_no_error(check_single_epirange_param("name", as.Date("2020-01-01"), required = FALSE))
  expect_error(check_single_epirange_param("name", NULL), "argument name is not an epirange_like")
  expect_no_error(check_single_epirange_param("name", NULL, required = FALSE))
  expect_error(check_single_epirange_param("name", list()), "argument name is not an epirange_like")
  expect_error(check_single_epirange_param("name", list(), required = FALSE), "argument name is not an epirange_like")
  expect_error(check_single_epirange_param("name", list("2020-01-01")), "argument name is not an epirange_like")

  # expect_error(check_single_epirange_param("name", c("2020-01-01", 20200102, as.Date("2020-01-03"), epirange(20200101, 20200102))), "argument name is not an epirange_like")
  # expect_error(check_single_epirange_param("name", c("2020-01-01", 20200102, as.Date("2020-01-03"), epirange(20200101, 20200102)), required = FALSE), "argument name is not an epirange_like")
  # expect_error(check_single_epirange_param("name", list("2020-01-01", 20200102, as.Date("2020-01-03"), epirange(20200101, 20200102))), "argument name is not an epirange_like")
  # expect_error(check_single_epirange_param("name", list("2020-01-01", 20200102, as.Date("2020-01-03"), epirange(20200101, 20200102)), required = FALSE), "argument name is not an epirange_like")
  expect_error(check_single_epirange_param("name", c("2020-01-01", 20200102, list())), "argument name is not an epirange_like")
})

test_that("check_epirange_param", {
  expect_no_error(check_epirange_param("name", "2020-01-01"))
  expect_no_error(check_epirange_param("name", "2020-01-01", required = FALSE))
  expect_no_error(check_epirange_param("name", 20200101))
  expect_no_error(check_epirange_param("name", 20200101, required = FALSE))
  expect_no_error(check_epirange_param("name", epirange(20200101, 20200102)))
  expect_no_error(check_epirange_param("name", epirange(20200101, 20200102), required = FALSE))
  # expect_no_error(check_epirange_param("name", as.Date("2020-01-01")))
  # expect_no_error(check_epirange_param("name", as.Date("2020-01-01"), required = FALSE))
  expect_error(check_epirange_param("name", NULL), "argument name is not an epirange_like")
  expect_no_error(check_epirange_param("name", NULL, required = FALSE))
  expect_error(check_epirange_param("name", list()), "argument name is not an epirange_like")
  expect_error(check_epirange_param("name", list(), required = FALSE), "argument name is not an epirange_like")
  expect_error(check_epirange_param("name", list("2020-01-01")), "argument name is not an epirange_like")

  expect_no_error(check_epirange_param("name", list(epirange(20200101, 20200102))))
  expect_error(check_epirange_param("name", c(epirange(20200101, 20200102))), "argument name does not accept vectors of epirange_likes, please use a list instead")

  # expect_error(check_epirange_param("name", c("2020-01-01", 20200102, as.Date("2020-01-03"), epirange(20200101, 20200102))), "argument name\\[3\\] is not an epirange_like")
  # expect_error(check_epirange_param("name", c("2020-01-01", 20200102, as.Date("2020-01-03"), epirange(20200101, 20200102)), required = FALSE), "argument name\\[3\\] is not an epirange_like")
  # expect_error(check_epirange_param("name", list("2020-01-01", 20200102, as.Date("2020-01-03"), epirange(20200101, 20200102))), "argument name\\[3\\]")
})
