name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: 4.0

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::devtools, any::rcmdcheck, any::styler, any::lintr, local::.

      - name: Style / Format
        shell: Rscript {0}
        run: styler::style_pkg(dry="fail")

      - name: Build Package
        shell: Rscript {0}
        run: |
          devtools::document()
          devtools::build()

      - name: Lint
        shell: Rscript {0}
        run: |
          devtools::load_all()
          lintr::lint_package('.')

      - uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--no-manual", "--as-cran")'
          build-args: 'c("--no-build-vignettes")'
          error-on: '"error"'

      - name: Test
        shell: Rscript {0}
        run: devtools::test()
