# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
#
# Edits from above workflow: also check pkgdown for PRs to `dev` branch, and
# update the documentation web site on pushes to `dev` branch.
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown

jobs:
  pkgdown:
    if: github.repository_owner == 'cmu-delphi'
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      DELPHI_EPIDATA_KEY: ${{ secrets.SECRET_EPIDATR_GHACTIONS_DELPHI_EPIDATA_KEY }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::., any::cli
          needs: website

      - name: Build site
        run: |
          override <- if (startsWith("${{ github.event_name }}", "pull_request")) {
              if ("${{ github.base_ref }}" == "main") {
                list(development = list(mode = "release", version_label = "light"))
              } else {
                list(development = list(mode = "devel", version_label = "success"))
              }
          } else {
              if ("${{ github.ref_name }}" == "main") {
                list(development = list(mode = "release", version_label = "light"))
              } else {
                list(development = list(mode = "devel", version_label = "success"))
              }
          }
          pkg <- pkgdown::as_pkgdown(".", override = override)
          cli::cli_rule("Cleaning files from old site...")
          pkgdown::clean_site(pkg)
          pkgdown::build_site(pkg, preview = FALSE, install = FALSE, new_process = FALSE)
          pkgdown:::build_github_pages(pkg)
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          clean: false
          branch: gh-pages
          folder: docs
